Repository AdhocAdam/smletsexchangeconnector, pull requests merged in 2018-12, with the labels that each got.

#104 Missing Dates for Keyword usage
  smletsExchangeConnector.ps1
Labels: bug, optimization/improvement

#108 #84 Override WI Type by keyword match (not ACS)
  smletsExchangeConnector.ps1
Labels: optimization/improvement

#107 #83 Consider BCC address with redirects
  smletsExchangeConnector.ps1
Labels: optimization/improvement

#102 Upgrade to v1.4.6
  smletsExchangeConnector.ps1
Labels: upgrade
